version: '3.8'

services:
  db:
    image: postgres:latest
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"
    depends_on:
      - db

  app:
    build: .
    env_file: ./.env
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/myapp
    ports:
      - "$APP_PORT:$APP_PORT"
    links:
      - db
    depends_on:
      - db

volumes:
  postgres-data:
